### ISSUE TITLE
你好，请问你家别墅建好了吗？

### ISSUE THREAD

**Issue by askme-gpt** [helloyuzz/Autodesk-Revit-Villa-Houseware#1]
你好，请问你家别墅建好了吗？
能否发一下造价表，我也想建一个。网上太多虚假宣传了，还是程序员靠谱。

**Comment by helloyuzz** [comment]
你好，你是想说做事务实吧。已经建好了！
自己su画图纸、买材料；另请施工队只负责施工，算半包性质。
另外，没有“造价表”，只有自己的一本手账，主要成本花销：原材料+人工成本（自己画图、出力就不算在内。但好处是，自己画图纸，可以完全按自己的设计来建）。

**Comment by askme-gpt** [comment]
厉害！是梦想中的房子吗？耗时多久？respect！能否把主要的花销发我参考一下？感谢，我准备用freeCAD来设计。你这个是专业设计建筑的，我看是需要付费的。

**Comment by helloyuzz** [comment]
是基本按照自己想法来的。设计还原度大概>95%吧。中间来回倒腾改微调了几次图纸（工人觉得麻烦不愿做）。搞完下来才发现，更多是享受“**又累又有成就感**”这个过程，毕竟自己的劳动成果，累并快乐！。 。

1. **地基**（8*17=136平米），两层建筑风格；
2. **费用**：钢筋、水泥、河沙、门、窗类、瓦、电线、pvc/ppr水管、照明等，累计≈17.5w，人工、临时工、挖机≈14.5w
3. **工价**：大工200/天，小工150/天，石匠300/天，木匠350/天（ps：中间给工人偶有发些小红包不算计内。）
4. **工期**：陆陆续续，差不多搞了有6-7个月左右。
5. 不计算自己的精力投入，搞好到入住，**累计花费：** 32w
6. ps：坐标重庆。

（每个地方工价可能不一致，仅参考。）

**Comment by helloyuzz** [comment]
> 厉害！是梦想中的房子吗？耗时多久？respect！能否把主要的花销发我参考一下？感谢，我准备用freeCAD来设计。你这个是专业设计建筑的，我看是需要付费的。

freeCAD完全可以。关键尺寸测量、标注正确就行。

**Comment by askme-gpt** [comment]
还原度能到95%，太厉害了！我之前在武汉装修了一套自己的房子，因为不太专业，搞一步看一步，最后结果跟自己想象中相去甚远。现在人工和材料可能要便宜点，不过你花了32w就全部搞好，已经相当好了。有发过短视频吗？留个号，我关注你，涨粉

**Comment by askme-gpt** [comment]
建造自己的房子，虽然有些辛苦，但肯定是很快乐的，这种状态应该很享受。我估计明年或者后年会翻建老家房子，在学freecad了，感觉这个搭建过程也蛮有趣的。

**Comment by helloyuzz** [comment]
感谢！。没精力搞视频那些。祝早日修好心仪的别墅！。🏡

**Comment by askme-gpt** [comment]
好的，多谢祝福。老兄做事很认真，材料配件都做了记录，很详实，感谢。

**Comment by helloyuzz** [comment]
一场持久战，遇到困难就给自己打鸡血！。。
刚开始兴奋那一阵，会半夜起来画图😂😂。仅作了部分记录。很耗精力的持久战；等做完你会发现😏......，钢筋、模板、架子、混凝土、木工、砌砖、抹灰、油漆、换锁、电工、防水、管工、电焊，好像什么都会了。。。简直了！。

**Comment by askme-gpt** [comment]
一样的，我之前在武汉装完了一套房子，我也是自己买材料，自己设计，直接找的工人施工，没有找包工头。😂😂，看这势头，这超级AI估计就这两年就出来了，80%的程序员会被干掉，我都准备转行了。
